flycheck-coala.el: json -> format output
coala/coala-emacs pull request #16
Opened 2017-05-14 20:14 UTC by fleimgruber

The ``--format`` option is more robust than the ``--json`` option when
logging output is mixed with the output of ``:command``;
``json-read-from-string`` breaks in this case.

Fixes https://github.com/coala/coala-emacs/issues/15

2017-05-29 13:49 UTC, sils commented on flycheck-coala.el
> +  :error-patterns  ((error (or "None" line) ":" (or "None" column) ":" (any "03") ":" (message))
why 03 and not 3?

2017-05-29 14:14 UTC, sils commented on flycheck-coala.el
> +  :error-patterns  ((error (or "None" line) ":" (or "None" column) ":" (any "03") ":" (message))
if 03 for a reason this needs a comment IMO

2017-05-29 15:25 UTC, userzimmermann requested changes
Hey @fleimgruber :) Thanks for the PR! Always great to see other Emacs enthusiasts in the coala community... I am only wondering about some little things ;)

2017-05-29 15:25 UTC, userzimmermann commented on flycheck-coala.el
> +  :error-patterns  ((error (or "None" line) ":" (or "None" column) ":" (any "03") ":" (message))
Can there really be severity `0`?

2017-05-29 15:25 UTC, userzimmermann commented on flycheck-coala.el
> +                    (warning (or "None" line) ":" (or "None" column) ":" (any "2") ":" (message))
`":2:"` should be enough instead of using `(any "...")`

2017-06-01 13:14 UTC, fleimgruber commented
Thanks for your comments!  I changed this to use `severity_str` and literal matches since these map nicely to `flycheck` error levels.  WDYT?

2017-06-07 08:51 UTC, fleimgruber commented on flycheck-coala.el
> +  :error-patterns  ((error (or "None" line) ":" (or "None" column) ":" (any "03") ":" (message))
I do not use numerical error codes any more, see below

2017-06-07 08:51 UTC, fleimgruber commented on flycheck-coala.el
> +  :error-patterns  ((error (or "None" line) ":" (or "None" column) ":" (any "03") ":" (message))
I do not use numerical error codes any more, see below.

2017-06-07 08:51 UTC, fleimgruber commented on flycheck-coala.el
> +                    (warning (or "None" line) ":" (or "None" column) ":" (any "2") ":" (message))
dito

2017-06-07 20:41 UTC, userzimmermann approved these changes

2017-06-07 20:41 UTC, userzimmermann commented
ack https://github.com/coala/coala-emacs/pull/16/commits/a9253f192403f067c9a62b47897fb51b4a9a3903

2017-06-07 20:41 UTC, userzimmermann commented
@rultor merge

2017-06-07 20:42 UTC, rultor commented
> @rultor merge

@userzimmermann OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11910-306918433)

2017-06-07 20:42 UTC, merged

2017-06-07 20:43 UTC, userzimmermann commented
@fleimgruber Now create the PR for https://github.com/coala/coala-emacs/issues/11 :)

2017-06-07 20:43 UTC, rultor commented
> @rultor merge

@userzimmermann Done! FYI, the full log is [here](http://www.rultor.com/t/11910-306918433) (took me 2min)